#
# This is a docker-compose file to build and start all Lakeside Mutual
# applications in a single command. Note that the applications will all
# run in production mode, so there won't be any live-reloading of changes
# or other development features. For development, we recommend to start
# the applications invidually or use the run_all_applications scripts.
#
# To build the Docker images:
#   docker-compose build
#
# To run the applications:
#   docker-compose up
#
# Note that you might have to adjust the REACT_APP_ and VUE_APP environment
# variables pointing to the backend services, depending on your hosting
# environment. By default, they point to localhost, which is fine when running 
# the services locally. In a cloud deployment, these should be changed to the 
# public domainname of the respective backend service.
# 
# To shut down the applications, simply terminate the previous command.
#

version: "3"
services:
  spring-boot-admin:
    build: lakesidemutual/spring-boot-admin
    image: lakesidemutual/spring-boot-admin
    networks:
      - lakeside
    ports:
      - "9000:9000"

  customer-core:
    build: lakesidemutual/customer-core
    image: lakesidemutual/customer-core
    networks:
      - lakeside
    environment:
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8110:8110"

  customer-management-backend:
    build: lakesidemutual/customer-management-backend
    image: lakesidemutual/customer-management-backend
    networks:
      - lakeside
    depends_on:
      - customer-core
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8100:8100"

  customer-management-frontend:
    build: lakesidemutual/customer-management-frontend
    image: lakesidemutual/customer-management-frontend
    networks:
      - lakeside
    depends_on:
      - customer-management-backend
    environment:
      - "REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=http://localhost:8080"
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=http://localhost:8100"
    ports:
      - "3020:80"

  policy-management-backend:
    build: lakesidemutual/policy-management-backend
    image: lakesidemutual/policy-management-backend
    networks:
      - lakeside
    depends_on:
      - customer-core
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8090:8090"
      - "61613:61613"
      - "61616:61616"

  policy-management-frontend:
    build: lakesidemutual/policy-management-frontend
    image: lakesidemutual/policy-management-frontend
    networks:
      - lakeside
    depends_on:
      - policy-management-backend
    environment:
      - "REACT_APP_POLICY_MANAGEMENT_BACKEND=http://localhost:8090"
    ports:
      - "3010:80"

  customer-self-service-backend:
    build: lakesidemutual/customer-self-service-backend
    image: lakesidemutual/customer-self-service-backend
    networks:
      - lakeside
    depends_on:
      - customer-core
      - policy-management-backend
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "POLICYMANAGEMENT_TCPBROKERBINDADDRESS=tcp://policy-management-backend:61616"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8080:8080"

  customer-self-service-frontend:
    build: lakesidemutual/customer-self-service-frontend
    image: lakesidemutual/customer-self-service-frontend
    networks:
      - lakeside
    depends_on:
      - customer-self-service-backend
      - customer-management-backend
      - policy-management-backend
    environment:
      - "REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=http://localhost:8080"
      - "REACT_APP_POLICY_MANAGEMENT_BACKEND=http://localhost:8090"
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=http://localhost:8100"
    ports:
      - "3000:80"
      
  risk-management-server:
    build: lakesidemutual/risk-management-server
    image: lakesidemutual/risk-management-server
    networks:
      - lakeside
    depends_on:
      - policy-management-backend
    environment:
      - "ACTIVEMQ_HOST=policy-management-backend"
      - "ACTIVEMQ_PORT=61613"
    ports:
      - "50051:50051"

networks:
  lakeside:
    name: lakeside
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: lakeside
