version: '3'

services:
  dmon:
    image: v1dmon/dmon:latest
    hostname: dmon
    restart: always
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ${DMON_ARGS:--i robot-shop -n robotshop_robot-shop -t 5s -r localhost -p 6379}
    depends_on:
      - web
