version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    dns: 10.32.0.1
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
    networks:
      - sockshop

  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    dns: 10.32.0.1
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
    networks:
      - sockshop

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    dns: 10.32.0.1
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    networks:
      - sockshop

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    dns: 10.32.0.1
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - sockshop

  carts:
    image: weaveworksdemos/carts:0.4.8
    dns: 10.32.0.1
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sockshop

  carts-db:
    image: mongo:3.4
    dns: 10.32.0.1
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop

  orders:
    image: weaveworksdemos/orders:0.4.7
    dns: 10.32.0.1
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sockshop

  orders-db:
    image: mongo:3.4
    dns: 10.32.0.1
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    dns: 10.32.0.1
    hostname: shipping
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sockshop

  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    dns: 10.32.0.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop

  rabbitmq:
    image: rabbitmq:3.6.8
    dns: 10.32.0.1
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    networks:
      - sockshop

  payment:
    image: weaveworksdemos/payment:0.4.3
    dns: 10.32.0.1
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    networks:
      - sockshop

  user:
    image: weaveworksdemos/user:0.4.4
    dns: 10.32.0.1
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
    networks:
      - sockshop

  user-db:
    image: weaveworksdemos/user-db:0.4.0
    dns: 10.32.0.1
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop

  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    dns: 10.32.0.1
    cap_drop:
      - all
    read_only: true
    hostname: user-simulator
    command: "-d 60 -r 200 -c 2 -h edge-router"
    networks:
      - sockshop

networks:
  sockshop:
    name: sockshop
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sockshop
